### PR TITLE
Move app to cmd

### PR DESCRIPTION
**Pull request by cgrigis**
Fixes ldsec/unlynxc/#22

### CODE REVIEW

**Comment by JoaoAndreSa** [comment]
@cgrigis this looks good to me and ready to be merged but I can't fix the conflicts with master (I recently accepted #35). Can you have a quick look at this so I can add these changes?

**Comment by mickmis** [comment]
> @cgrigis this looks good to me and ready to be merged but I can't fix the conflicts with master (I recently accepted #35). Can you have a quick look at this so I can accept these changes?

I just changed the target to `dev`.

**Comment by cgrigis** [comment]
> > @cgrigis this looks good to me and ready to be merged but I can't fix the conflicts with master (I recently accepted #35). Can you have a quick look at this so I can accept these changes?

Sorry, I missed that.

> I just changed the target to `dev`.

Looks like it merges now (failed dockercloud though?).
Do you still need me to do anything?

**Comment by JoaoAndreSa** [comment]
Nope @cgrigis its perfect like this. This ci/dockerclould check is deprecated and I already removed it from the mandatory checks, but awkwardly is still shows up here.

**Pull request merged**
